#!/usr/bin/env bash

source /scripts/logger.sh

log_start "Starting the celerybeat..."

fdmove -c 2 1 exec s6-setuidgid service /etc/services.d/gitlab-tools-bgtask/service.sh | eval "/usr/bin/mawk -W interactive '{print \"[${GREEN}bgtask${RESET}]\",\$0}'"
