#!/usr/bin/env bash

source /scripts/logger.sh

log_start "Starting the celerybeat..."

fdmove -c 2 1 runuser -l service -c "cd /opt/gitlab-tools && source venv/bin/activate && python manage.py celerybeat --config_prod --schedule=/conf/celery_beat.db --pid=/tmp/celerybeat.pid" | eval "/usr/bin/mawk -W interactive '{print \"[${GREEN}gitlab-tools-bgtask${RESET}]\",\$0}'"
