stages:
  - docker
  - post

include:
  - project: devops/pipes
    file: /templates/docker-build-dockerhub.gitlab-ci.yml

  - project: devops/pipes
    file: /templates/update-docker-hub-readme.gitlab-ci.yml

variables:
  DOCKER_IMAGE_NAME: cenk1cenk2/gitlab-tools
  README_DESCRIPTION: |
    Runs Salamek/gitlab-tools in a container, which enables pull/push mirroring to Gitlab.
  DOCKERFILE_CONTEXT: .
  DOCKER_IMAGE_TAGS: latest

build-docker-image:
  only:
    refs:
      - main
      - tags

update-docker-hub-readme:
  only:
    refs:
      - main
      - tags
