stages:
  - docker
  - post

include:
  - project: devops/pipes
    file: /templates/docker-build-dockerhub.gitlab-ci.yml
    ref: main

  - project: devops/pipes
    file: /templates/update-docker-hub-readme.gitlab-ci.yml
    ref: main

build-docker-image:
  variables:
    DOCKERFILE_CONTEXT: .
    DOCKER_IMAGE_NAME: cenk1cenk2/gitlab-tools
    IMAGE_TAGS: latest
  only:
    refs:
      - main
      - tags

update-docker-hub-readme:
  variables:
    README_REPOSITORY: cenk1cenk2/gitlab-tools
    README_FILE: ./README.md
    README_DESCRIPTION: |
      Runs Salamek/gitlab-tools, a tool to enable pull/push mirroring to Gitlab from other Git sources in a container.
  only:
    refs:
      - main
      - tags
