stages:
  - publish

.docker-common:
  stage: publish
  trigger:
    include:
      - project: devops/pipes
        file: /templates/docker-build-dockerhub.gitlab-ci.yml
        ref: main
    strategy: depend

publish:
  extends: .docker-common
  variables:
    DOCKERFILE_CONTEXT: .
    DOCKER_IMAGE_NAME: cenk1cenk2/gitlab-tools
    IMAGE_TAGS: latest
  only:
    refs:
      - main
      - tags
