version: '3.7'

services:
  gitlab-tools:
    image: cenk1cenk2/gitlab-tools:test
    build:
      context: .
    restart: always
    ports:
      - 8080:80
    env_file:
      - ./.env
    depends_on:
      - gitlab-tools-db
      - rmq
      - redis

  gitlab-tools-db:
    image: postgres:13-alpine
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: gitlab-tools
      POSTGRES_USER: gitlab-tools
      POSTGRES_PASSWORD: something

  rmq:
    image: rabbitmq:alpine

  redis:
    image: redis:alpine
