GITLAB_SSH: ${GT_GITLAB_SSH}
GITLAB_APP_ID: ${GT_GITLAB_APP_ID}
GITLAB_APP_SECRET: ${GT_GITLAB_APP_SECRET}
GITLAB_URL: ${GT_GITLAB_URL}
HOST: 0.0.0.0
PORT: '80'
SERVER_NAME: ${GT_SERVER_NAME}
SECRET_KEY: ${GT_SECRET_KEY}
SQLALCHEMY_DATABASE_URI: ${GT_DATABASE_URI}
# TODO: add configuration parameters and delete the redis, rmq instance
CELERY_BROKER_URL: ${GT_CELERY_BROKER_URL}
CELERY_TASK_LOCK_BACKEND: ${GT_CELERY_TASK_LOCK_BACKEND}
USER: 'service'
