GITLAB_APP_ID: ${GT_GITLAB_APP_ID}
GITLAB_APP_SECRET: ${GT_GITLAB_APP_SECRET}
GITLAB_URL: ${GT_GITLAB_URL}
HOST: 0.0.0.0
PORT: '8080'
SERVER_NAME: ${GT_SERVER_NAME}
SECRET_KEY: ${SECRET_KEY}
SQLALCHEMY_DATABASE_URI: ${GT_DATABASE_URI}
USER: service
